### ISSUE TITLE
hardcoded "web" dir

### ISSUE THREAD

**Issue by masiorama** [OscarBarrett/craft-twig-webpack-extension#1]
Hello, I have an issue as regards the fact that you hardcoded the "web" directory inside the init function of your plugin.

As stated in the craft documentation, it is possible to have a different name for that directory (https://docs.craftcms.com/v3/directory-structure.html), as in my case, htdocs.

Any idea how to fix this to my needs?
Thanks in advance!

**Comment by OscarBarrett** [comment]
Thanks for reporting this - I've only ever used the standard dir so I never ran into this problem.

The best solution for now is probably to use the value of `$_SERVER['DOCUMENT_ROOT']` instead of hardcoding `web`.

In the future I might consider making `manifestPath` the full path to the file, which  could be useful for example if the manifest is stored outside of the document root.

I've pushed a fix to [dev-master](/OscarBarrett/craft-twig-webpack-extension/tree/dev-master). Could you give that a go and let me know if it works for you?

**Comment by masiorama** [comment]
Thanks! As far as I know it should be 
`Craft::getAlias('@webroot')`
inside a plugin.
Thanks!

**Comment by OscarBarrett** [comment]
Thanks! I did find that but I just realised that I had tried `Craft::getRootAlias` instead which is why I didn't have any luck with that and fell back to $_SERVER. I've switched to using `getAlias`.

Fixed in 1.0.3.
